### ISSUE TITLE
Add Demo 4 Documentation to GitHub

### ISSUE THREAD

**Issue by chichi091** [COS301-SE-2022/Map-out-game-reserves-using-aerial-photographs#311]

**Comment by ZoeLiebenberg** [comment]
![Deployment Diagram](https://user-images.githubusercontent.com/82899425/193235520-d2cc1039-25ec-4c5e-b2ea-3abda2a5f408.jpg)
![Architectural Diagram](https://user-images.githubusercontent.com/82899425/193235536-72a57bb0-4aa1-49a5-96a5-7aae79575756.jpg)
